### ISSUE TITLE
Become a Member

### ISSUE THREAD

**Issue by TilmanLewis** [surj-to/main-website#10]
https://www.surjtoronto.com/join
Here are some things to know about becoming a member:
1. Members are expected to agree our values and ways of working.
Word missing: "... to agree with our values ..." or "... to agree to our values ..."
2. We believe in resource distribution. Change "We move money, time, energy, and resources out of white communities and in support of Black, Indigenous, and People of Colour-led movements, communities, and spaces." to
We move money, time, energy, and resources out of white communities and in support of movements, communities, and spaces led by Black, Indigenous, and racialized people.

**Comment by chelsea-pb** [comment]
Done!
