### ISSUE TITLE
Should we transfer pre 2021 blogs?

### ISSUE THREAD

**Issue by chelsea-pb** [surj-to/main-website#13]
2020:
- [ ] SURJ Toronto Statement on #COVIDZero
- [ ] SURJ TO Supports Call to Defund Hamilton Police
- [ ] From Defunding Police to Abolition
- [ ] How white folks can take anti-racist action in COVID 19
- [ ] 5 Ways to Take Anti-Racist Action During COVID-19
- [ ] Do I have capacity for mutual aid? A Flow Chart
- [ ] COVID-19 Ontario Coalition Against Poverty Letter Campaign
- [ ] Migrant Rights Are a Full Time Fight
- [ ] In Solidarity with the Wet’suwet’en Hereditary Chiefs
- [ ] Join The SURJTO Reading Group

2019

- [ ] Yan Chen Fights for climate justice in Scarborough North
- [ ] Supporting Sex Workers in Toronto
- [ ] Close the Concentration Camps
- [ ] CONCERNED TORONTONIANS DELIVER DEMANDS ON IMMIGRATION DETENTION TO CHRYSTIA FREELAND, MINISTER OF FOREIGN AFFAIRS
- [ ] SURJ In Conversation with Activist and Scholar, Angela Davis
- [ ] Summer Family Dance Party
- [ ] Grassy Narrows Action
- [ ] Migrant Rights Network Action
- [ ] Public Education is a Racial Justice Issue

**Comment by TilmanLewis** [comment]
On a case-by-case basis, a few of them might be valuable to keep, e.g., In Solidarity with the Wet'suwet'en Chiefs, perhaps; Join the SURJ TO Reading Group, no. But I think if no one is raising that they're missing these blogs, it's low priority.

**Comment by chelsea-pb** [comment]
@dreymoreau this is the issue I was wondering if you had the capacity to work on?

**Comment by chelsea-pb** [comment]
@dreymoreau as we chatted about, we can move forward with this task. At the meeting, please suggest this as an activity that the student can also help with.

**Comment by skyspace88** [comment]
this task is finished! :-) @chelsea-pb

**Comment by chelsea-pb** [comment]
Woohoo! Congratulations!!
