### ISSUE TITLE
Feedback Form Suggestion - Become a member reference to "mad"

### ISSUE THREAD

**Issue by chelsea-pb** [surj-to/main-website#16]
From the feedback form:
hi! i noticed that on the "become a member" page, there is a question at the end that reads: "Do you identify as disabled, Deaf, and/or mad?" would it be possible to have an asterisk on "mad" and maybe a brief definition for folks who may not have come across this terminology but experience mental illness, neurodivergence, etc... I only learned about mad studies in the last year myself and i think in the interest of accessibility it would be good to explain the language.

**Comment by TilmanLewis** [comment]
Interesting - that might be a language choice to run by the accessibility folks, where I think it originated

**Comment by chelsea-pb** [comment]
Look into whether we can * and link to an article

**Comment by chelsea-pb** [comment]
https://madnessnetworknews.com/definitions/
https://mlauferwriter.medium.com/what-is-mad-studies-27f8df529619
