### ISSUE TITLE
check relevance of ASL video

### ISSUE THREAD

**Issue by TilmanLewis** [surj-to/main-website#17]
When you get a chance, please see if the accessibility group has capacity to have the ASL video on https://www.surjtoronto.com/blog/accessibility reviewed to make sure it's still reasonably current

**Comment by chelsea-pb** [comment]
Kate to watch for relevance

**Comment by TilmanLewis** [comment]
So, following up on a Comms meeting discussion, I did ask Kate to review the ASL video. She points out, hilariously, that it's captioned, so no further translation is necessary. It gives broad strokes, and almost all of the content is evergreen and just fine.
There are two pieces that could ideally use an update one fine day:
 The list of teams/working groups is out of date: there's no mention of campaigns and/or defunding, and team names have changed (e.g., Action not Mobilization; LARRE not Fundraising / Education)
 The video refers to an accountability panel, which no longer reflects are current approach to accountability. It says "We maintain accountability with a panel of BIPOC organizers and groups that provide consultation on the work we do ..." That section should ideally be updated.
CONCLUSION: Probably harmless to leave this video up as is for the time being. When we next have an uptick in Deaf involvement / interest in SURJ, a good project would be to create an ASL video with some updated content.

**Comment by chelsea-pb** [comment]
@TilmanLewis are we good to close this issue?

**Comment by TilmanLewis** [comment]
I'll close it on GitHub, yes. 
It would be amazing if somehow the thought wasn't lost, but this perhaps isn't the place for that.

**Comment by chelsea-pb** [comment]
If you close the issue it will keep a record of the issue including the
comments!
