### ISSUE TITLE
links in Our Teams section

### ISSUE THREAD

**Issue by TilmanLewis** [surj-to/main-website#18]
Our Teams (bottom of https://www.surjtoronto.com/about)
Some of the blurbs have links and others don't. I'd lean to adding some more so it looks more complete, do you agree?
Action might link to a Featured Actions anchor on the Home Page?
Can we give contact information for the CT? It might just be to the Contact Us page

**Comment by chelsea-pb** [comment]
I like this idea! I could add:

- [x]  Featured actions to Action
- [x] newsletter signup to Comms (plus the socials that are there)
- [x] contact page for CT. 

Thoughts? Do we need anything for Ad Hoc groups?

**Comment by chelsea-pb** [comment]
Note: we will need to update the Campaigns link if we create a new campaigns landing page (which I think is likely)

**Comment by TilmanLewis** [comment]
No link for Ad Hoc groups makes sense to me - that one's "ad hoc", different from the rest

**Comment by chelsea-pb** [comment]
@TilmanLewis are we good to close this issue?
