### ISSUE TITLE
calendar mobile display

### ISSUE THREAD

**Issue by TilmanLewis** [surj-to/main-website#20]
I don't know what tweaks SquareSpace allows to the calendar function, but it may not be a super mobile-friendly display atm. 

I wanted to check the website calendar to double-check that the Alternatives to 911 series had been added. I happened to be on my phone (Android, using Safari), and at first glance, it seemed like there were no events in August (see screenshot).

![Screenshot_20230807-123923](https://github.com/surj-to/main-website/assets/135617156/6d32faaa-0f8c-4ffd-80fd-2668efa4ea21)

On further investigation, I could find the workshops by navigating to Events, and also by selecting the appropriate calendar dates (Aug. 2, 16, 23) - but until you do that, there's no indication that a date has an event associated with it.

**Comment by chelsea-pb** [comment]
@TilmanLewis looked into this, and unfortunately this is the only option.

**Comment by TilmanLewis** [comment]
thanks, oh well
