### ISSUE TITLE
snippet for search results

### ISSUE THREAD

**Issue by TilmanLewis** [surj-to/main-website#21]
I don't know where Google pulls snippets from, but on the home page, it's skipping the banner text and starting with the first text block on the page, "That is why..." (see image attached)
When we create a blog, there's a field to define the associated snippet. Is there a comparable function for the site as a whole, so we can direct search engines to a meaningful blurb, i.e., add "No one is free until everyone is free" before "That is why" or skip ahead to start "SURJ Toronto is..."
![search-results](https://github.com/surj-to/main-website/assets/135617156/b1df0158-00fc-4c4d-a1e8-4d464ff69bfe)

**Comment by chelsea-pb** [comment]
@TilmanLewis I was able to fix this, please close when you have a chance.

**Comment by TilmanLewis** [comment]
yay!
