### ISSUE TITLE
Home page wording

### ISSUE THREAD

**Issue by TilmanLewis** [surj-to/main-website#7]
https://www.surjtoronto.com/
Our mission is guided by a a long-standing call from Black, Indigenous and racialized leaders to organize white people. We organize with the following movement partners on an ongoing basis. We also move money to these organizations.
1. delete repeated word "is guided by a a ..."
2. Let's end this blurb "We also move money to these and other grassroots organizations."
I got confused about selected logos on the home page but then a different batch when you hit the link.

**Comment by chelsea-pb** [comment]
Done!
