### ISSUE TITLE
Campaigns We Support

### ISSUE THREAD

**Issue by TilmanLewis** [surj-to/main-website#8]
https://www.surjtoronto.com/blog/campaigns-we-support
1. In the #StatusForAll blurb, "poster fundraiser" is a dead link (should go to https://www.surjtoronto.com/blog/support-statusforall-mwac-poster)
2. I wrote the Decolonial Solidarity blurb, and I'd like to beef up the ending to be more in line with #StatusForAll.
Change "SURJ Toronto has participated in the adopt-a-branch information campaign and supported actions at corporate headquarters such as the 2023 April Fossil Fools’ Day rally in the lead-up to the bank’s AGM." to 
SURJ Toronto has participated in the adopt-a-branch information campaign, raised funds for Gidemten checkpoint, and supported actions at corporate headquarters such as the 2023 April Fossil Fools’ Day rally in the lead-up to the bank’s AGM. Stay tuned to SURJ Toronto and Decolonial Solidarity socials for ongoing calls to action.

**Comment by chelsea-pb** [comment]
Done!
